export const WHATSAPP_NUMBER = '212613205033';

export const ADMIN_PASSWORD = 'omnour2024'; // Change this!

export const INITIAL_PRODUCTS = [
  {
    id: '1',
    name: 'الشبّاكية',
    description: 'حلوى مقرمشة بالسمسم والعسل، تُقلى وتُغطس في العسل وماء الزهر. من أشهر حلويات رمضان الأصيلة.',
    category: 'حلويات تقليدية',
    price: 85,
    unit: 'كيلو',
    image: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=600&q=80',
    badge: '🔥 الأكثر طلباً',
    stock: 15,
    featured: true,
    createdAt: new Date('2024-01-10').toISOString(),
  },
  {
    id: '2',
    name: 'كعب الغزال',
    description: 'معجنات هلالية الشكل محشوة باللوز والقرفة، مرشوشة بالسكر البودرة. من أرقى الحلويات المغربية.',
    category: 'حلويات بالعجين',
    price: 120,
    unit: 'كيلو',
    image: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=600&q=80',
    badge: '⭐ مميز',
    stock: 8,
    featured: true,
    createdAt: new Date('2024-01-12').toISOString(),
  },
  {
    id: '3',
    name: 'السلّو',
    description: 'خليط من الدقيق المحمص واللوز والسمسم مع العسل والزبدة والتوابل. غذاء مقوّي ولذيذ.',
    category: 'حلويات تقليدية',
    price: 70,
    unit: 'كيلو',
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80',
    badge: '💛 تراثي',
    stock: 20,
    featured: false,
    createdAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: '4',
    name: 'البريوات باللوز',
    description: 'مثلثات من عجينة الورقة محشوة باللوز والقرفة، مقلية ومغموسة في العسل وماء الزهر.',
    category: 'حلويات بالعجين',
    price: 95,
    unit: 'كيلو',
    image: 'https://images.unsplash.com/photo-1533910534207-90f31029a78e?w=600&q=80',
    badge: '❤️ مشهور',
    stock: 12,
    featured: true,
    createdAt: new Date('2024-01-18').toISOString(),
  },
  {
    id: '5',
    name: 'الغريبة',
    description: 'بسكويت طري يذوب في الفم مصنوع من اللوز أو الكوكو. خفيف وشهي مع كأس أتاي.',
    category: 'بسكويت',
    price: 75,
    unit: 'كيلو',
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&q=80',
    badge: null,
    stock: 18,
    featured: false,
    createdAt: new Date('2024-01-20').toISOString(),
  },
  {
    id: '6',
    name: 'المحنشة',
    description: 'حلوى الثعبان الأسطورية — طبقات من عجينة الورقة محشوة بعجينة اللوز وماء الزهر. للمناسبات الخاصة.',
    category: 'حلويات بالعجين',
    price: 150,
    unit: 'قطعة',
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&q=80',
    badge: '👑 حصري',
    stock: 5,
    featured: true,
    createdAt: new Date('2024-01-22').toISOString(),
  },
  {
    id: '7',
    name: 'الفقاس',
    description: 'بسكويت محمص مرتين باللوز والسمسم والينسون. مثالي مع الشاي المغربي بالنعناع.',
    category: 'بسكويت',
    price: 60,
    unit: 'كيلو',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    badge: null,
    stock: 25,
    featured: false,
    createdAt: new Date('2024-01-25').toISOString(),
  },
  {
    id: '8',
    name: 'بسطيلة حلوة',
    description: 'كعكة احتفالية من طبقات الورقة المقرمشة، الكريمة، واللوز مع رشة قرفة وسكر. للأعراس والمناسبات.',
    category: 'حلويات بالعجين',
    price: 180,
    unit: 'قطعة',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&q=80',
    badge: '🎉 جديد',
    stock: 4,
    featured: true,
    createdAt: new Date('2024-02-01').toISOString(),
  },
];

export const CATEGORIES = ['الكل', 'حلويات تقليدية', 'حلويات بالعجين', 'بسكويت'];
export const UNITS = ['كيلو', 'غرام', 'قطعة', 'علبة', 'صينية'];
export const BADGES_LIST = ['', '🔥 الأكثر طلباً', '⭐ مميز', '💛 تراثي', '❤️ مشهور', '👑 حصري', '🎉 جديد', '🌟 جودة عالية'];
